### ISSUE TITLE
HI!

### ISSUE THREAD

**Issue by anandijain** [Lucaman99/Lucaman99#1]
close this shitpost chief

**Comment by Lucaman99** [comment]
🤔 🤔 🤔

**Comment by anandijain** [comment]
can I have xanadu internship?

**Comment by seyonechithrananda** [comment]
i too would like xanadu internship plz

**Comment by Lucaman99** [comment]
Sorry guys, I don’t think I’m at liberty to give them out 😩

**Comment by seyonechithrananda** [comment]
but I helped u build the QGNN, that should give me some rep!

**Comment by Lucaman99** [comment]
Nahhhhh
